version: '3'
services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - ./Postgres_data/var/lib/postgresql:/var/lib/postgresql
    environment:
      - PSOTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobsf
  mobsf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - POSTGRES=True
    volumes:
      - ./MobSF_data:/root/.MobSF
    ports:
     - "8989:8000"
  
